export const types = {
  LOGIN_SUCCESS: "auth/LOGIN_SUCCESS",
  LOGIN_FAIL: "auth/LOGIN_FAIL",
  INIT_APP: "auth/INIT_APP",
  SET_PRIVILEGES: "auth/SET_PRIVILEGES",
  SET_LOADING: "auth/SET_LOADING",
};
