export const types = {
  SET_NEW_TABLE: "table/SET_NEW_TABLE",
  SET_PAGE: "table/SET_PAGE",
  SET_PAGE_SIZE: "table/SET_PAGE_SIZE",
  TOGGLE_IS_SEARCH: "table/TOGGLE_IS_SEARCH",
  SET_SORT_KEY: "table/SET_SORT_KEY",
  SET_SEARCH_PARAMS: "table/SET_SEARCH_PARAMS",
};
